title = "jouyouyun's blog"
baseURL = "https://jouyouyun.github.io"
languageCode = "en"
theme = "ananke"

DefaultContentLanguage = "zh"
#SectionPagesMenu = "main" # equal with Archives
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
enableEmoji = true
copyright = "jouyouyun"            # default: author.name ↓        # 默认为下面配置的author.name ↓

[author]                  # essential                     # 必需
  name = "jouyouyun"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[params]
  text_color = ""
  since = "2014"            # Site creation time          # 站点建立时间
  author = "jouyouyun"
  favicon = ""
  site_logo = ""
  description = "jouyouyun's blog."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  dateFormatToUse = "2014-01-01"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/jouyouyun"
