#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: post
#+SEQ_TODO: TODO NEXT DRAFT DONE
#+FILETAGS: post
#+OPTIONS:   *:t <:nil timestamp:nil toc:nil ^:{}
#+HUGO_AUTO_SET_LASTMOD: t
#+TITLE: 校园招聘内容
#+DATE: 2019-03-25T19:38:21+08:00
#+HUGO_TAGS: cursor
#+HUGO_CATEGORIES: BLOG
#+HUGO_DRAFT: true

整理下校园招聘需要问道的知识点.

** 语言基础

*** Python

**** 三元运算子

=[on true] if [expression] else [on false]=

=print("Hi") if a<b else print("Bye")=

<!--more-->

**** Lambda

=Lambda= 的使用


**** 装饰器

使用装饰器记录函数执行的日志, 支持 =level=


**** 变量的内存分配


**** 元组与数据


*** C/C++

**** 关键字

=static/extern/const=

=const int *p= 与 =int* const p=

**** 指针

指针数组和数组指针, 如 int (*p)[5]; 和 int *p[5];

**** typedef

定义新的类型,如 typedfe int ARRAY[5]; 定义了一个有5个int元素的类型 ARRAY

复杂类型简化及使用

typedef int (*A) (char, char); A 可以怎么初始化


**** Lambda

=Lambda= 传递参数

#+BEGIN_SRC shell
[]      // 沒有定义任何变量, 使用未定义变量会引发错误
[x, &y] // x以传值方式传入 (默认), y以引用方式传入
[&]     // 任何被使用到的外部变量都隐式地以引用方式加以引用
[=]     // 任何被使用到的外部变量都隐式地以传值方式加以引用
[&, x]  // x显式地以传值方式加以引用, 其余变量以引用方式加以引用
[=, &z] // z显式地以引用方式加以引用, 其余变量以传值方式加以引用

另外有一点需要注意: 对于 [=] 或 [&] 的形式, lambda 表达式可以直接使用 this 指针, 但是, 对于 [] 的形式, 如果要使用 this 指针, 必须显式传入:
[this]() { this->someFunc(); }();
#+END_SRC

**** 智能指针

几种指针之间的区别

`unique_ptr, shared_ptr, weak_ptr`

unique_ptr不能共享, 可以通过 move 来传递

shared_ptr使用计数机制来表明资源被几个指针共享, 可以通过成员函数use_count()来查看资源的所有者个数.
调用release()时，当前指针会释放资源所有权，计数减一。当计数等于0时，资源会被释放。
处了可以通过new来构造，还可以通过传入auto_ptr, unique_ptr,weak_ptr来构造。

weak_ptr是用来解决shared_ptr相互引用时的死锁问题,如果说两个shared_ptr相互引用,那么这两个指针的引用计数永远不可能下降为0,资源永远不会释放
。它是对对象的一种弱引用，不会增加对象的引用计数，和shared_ptr之间可以相互转化，shared_ptr可以直接赋值给它，它可以通过调用lock函数来获得shared_ptr


何时使用


*** GoLang

**** Structure

#+BEGIN_SRC go
type student struct {
	Name string
	Age  int
}

func pase_student() {
	m := make(map[string]*student)
	stus := []student{
		{Name: "zhou", Age: 24},
		{Name: "li", Age: 23},
		{Name: "wang", Age: 22},
	}
	for _, stu := range stus {
		m[stu.Name] = &stu
	}
	for k, v := range m {
		fmt.Println(k, v)
	}
}
#+END_SRC

**** Params Pass

=Go=  的参数传递是 *值传递*, 传递的是一个副本.
但对于 =slice, map, channel, interface, func= 等类型的变量会在声明时创建标头(=header=).
=header= 里包含一个指针, 执行底层的数据结构, 所以这些类型的元素修改会一同生效.

在 =struct A= 中 =func(A)= 类型的方法对 =A= 的修改在外部并不会生效, =func(*A)= 的才会生效.

#+BEGIN_SRC go
func main() {
	var list = []string{"hello", "world"}
	var set = map[string]string{
		"1": "test1",
	}
	modify(list, set)
	fmt.Println(list)
	fmt.Println(set)
}

func modify(list []string, set map[string]string) {
	list[1] = "Jay"
	list = append(list, "Test")
	set["2"] = "test2"
}
#+END_SRC

**** defer

多个 =defer= 的执行顺序, 先进后出

=defer= 在 =RTE= 之前执行

匿名返回值是在 =RET= 执行时声明的, 有名返回值是函数创建时声明的, =defer= 只能访问有名返回值

=return= 时分为二个步骤:

1. 给返回值赋值
2. 执行 =RET= 指令

因此 =defer, return= 的执行顺序是:

1. 返回值赋值
2. =defer= 执行
3. =RET= 执行

=defer= 推迟的只是函数执行的时间, 函数参数的值在声明时就会计算(打印时间的例子)

#+BEGIN_SRC go
package main

import (
	"fmt"
	"time"
)

func main() {
	defer p(time.Now())
	fmt.Println(test1())
	fmt.Println(test2())
	fmt.Println(*test3())
	time.Sleep(time.Second * 10)
	p(time.Now())
}

func test1() (x int) {
	x = 1
	defer func() {
		x++
	}()
	return (x + 1)
}

func test2() int {
	var x = 1
	defer func() {
		x++
	}()
	return (x + 1)
}

func test3() *int {
	var x = 1
	defer func() {
		x++
	}()
	return &x
}

func p(t time.Time) {
	fmt.Println(t)
}
#+END_SRC

**** channel

随机生成 =5= 个字符串并打印出来

=chan= 不指定 =capacity= 与指定的区别, 不指定时发送值也会阻塞

使用 =4= 个 =chan= 输出以下字符串, 长度为 =20= :

#+BEGIN_SRC go
// abcdabcdabc...
// bcdabcdabcd...

package main

import (
	"fmt"
)

func main() {
	var chs = make([]chan byte, 4)

	var gen = func(i int) {
		chs[i] <- byte('a' + i)
	}

	for i := 0; i < 4; i++ {
		chs[i] = make(chan byte, 1)
		gen(i)
	}

	var p = func(i int) string {
		var ret string
		var count = 0
		for count < 20 {
			count++
			ret += fmt.Sprint(string([]byte{<-chs[i]}))
			gen(i)
			i++
			if i == 4 {
				i = 0
			}
		}
		return ret
	}

	// print 'abcdabcdabc...'
	fmt.Println(p(0))

	// print 'bcdabcdabc...'
	fmt.Println(p(1))
}
#+END_SRC


*** Web

**** Flex

=flex= 布局

**** XSS

跨站脚本攻击是一种代码注入攻击.
本质是：恶意代码未经过滤, 与网站正常的代码混在一起;
浏览器无法分辨哪些脚本是可信的, 导致恶意脚本被执行.

在处理输入时, 以下内容都不可信:

- 来自用户的 UGC 信息
- 来自第三方的链接
- URL 参数
- POST 参数
- Referer (可能来自不可信的来源)
- Cookie

举例说明, 一个具体的攻击例子

**** CSRF

举例说明, 一个具体的攻击例子

- =html= 中通过 =img/meta/iframe/script/audio/video/embed/background= 等标签或 =css= 属性来访问(=GET=)
- =JSON HiJacking= 针对返回数据类型是 =JSON= 的请求, 通过 =js= 来实现

如返回一个 =JSON Array=, 再请求返回前先劫持 =Array= 对象, 如下：

#+BEGIN_SRC javascript
<script>
var JackObj;
Array = function() {
  JackObj = this;
};
</script>
<script src="http://api.jouyouyun.top/user"></script>
#+END_SRC

**** 界面劫持

- 点击劫持
- 拖放劫持
- 触摸劫持

实现原理：

透明层 + iframe

**** CSS

- display:none和visibility:hidden的区别

  display:none  隐藏对应的元素，在文档布局中不再给它分配空间，它各边的元素会合拢，
就当他从来不存在

  visibility:hidden  隐藏对应的元素，但是在文档布局中仍保留原来的空间

- 盒子模型

  从中心向外： 内容 -> padding -> border -> margin

- CSS 选择器

  优先级就近原则，同权重情况下样式定义最近者为准.
  =!important >  id > class > tag=,
  important 比 内联优先级高,但内联比 id 要高

  + id 选择器 #id
  + 类选择器 .class
  + 标签选择器 div
  + 相邻选择器 div + span
  + 子选择器 ul > li
  + 后代选择器 li a
  + 通配符选择器 *
  + 属性选择器 a[rel == "external"]
  + 伪类选择器 a:hover, li:nth-child

**** Doctype作用

<!DOCTYPE> 声明位于文档中的最前面，处于 <html> 标签之前。告知浏览器以何种模式来渲染文档.

DOCTYPE不存在或格式不正确会导致文档以混杂模式呈现


**** javascript

- let 与 var 的区别
- 闭包含义, 实现 =id= 自增
- =cookie= 隔离或请求时不带上 =cookie=, 设置 =domain=
- 判断变量原型 =instanceof= 或原型链 =__proto__=
- 描述new一个对象的过程

  1. 创建一个新对象
  2. this指向这个新对象
  3. 执行代码给this赋值
  4. return this

- 写一个能遍历对象和数组的通用forEach函数

#+BEGIN_SRC js
function forEach(obj, fn) {
  if (obj instanceof Array) {
    obj.forEach(function (item, index) {
      fn(index, item);
    })
  } else {
    for (var key in obj) {
      if (obj.hasOwnProperty(key)) {
        fn(key, obj[key]);
      }
    }
  }
}

var arr = [1, 2, 3, 4];
forEach(arr, function (index, item) {
  console.log(index + ',' + item);
});

var obj = {
  x: 10,
  y: 20
};
forEach(obj, function (index, item) {
  console.log(index + ',' + item);
});
#+END_SRC

- 实现一个判断 x 是否是整数的函数

#+BEGIN_SRC js
// 可以将 x 转换成10进制，判断和本身是不是相等即可
function isInteger(x) {
    return parseInt(x, 10) === x;
}
#+END_SRC

**** typescript


**** 页面加载流程

1. 当发送一个URL请求时，不管这个URL是Web页面的URL还是Web页面上每个资源的URL，
浏览器都会开启一个线程来处理这个请求，同时在远程DNS服务器上启动一个DNS查询。
这能使浏览器获得请求对应的IP地址

2.  浏览器与远程Web服务器通过TCP三次握手协商来建立一个TCP/IP连接。
该握手包括一个同步报文，一个同步-应答报文和一个应答报文，这三个报文在浏览器和服务器之间传递。
该握手首先由客户端尝试建立起通信，而后服务器应答并接受客户端的请求，
最后由客户端发出该请求已经被接受的报文

3. 一旦TCP/IP连接建立，浏览器会通过该连接向远程服务器发送HTTP的GET请求。
远程服务器找到资源并使用HTTP响应返回该资源，值为200的HTTP响应状态表示一个正确的响应

4. 此时，Web服务器提供资源服务，客户端开始下载资源


**** ajax过程

1. 创建XMLHttpRequest对象,也就是创建一个异步调用对象
2. 创建一个新的HTTP请求,并指定该HTTP请求的方法、URL及验证信息.
3. 设置响应HTTP请求状态变化的函数
4. 发送HTTP请求
5. 获取异步调用返回的数据
6. 使用JavaScript和DOM实现局部刷新

**** 前端框架

=vue.js/angular=

数据绑定

父子通信

=angular= 代码架构


** 面向对象

- 继承
- 成员类型
- 操作符重载
- 方法重写
- 多态

** 数据结构

*** 链表

反序, 环检测

排序

合并

交叉链表求交点: 两个链表相交则尾一定相同, 所以从尾部开始遍历

*** 栈

实现

*** 队列

实现


*** 树

遍历:

- 先序

  先访问根节点，然后前序遍历左子树，再前序遍历右子树

- 中序

  从根节点开始, 中序遍历根节点的左子树，然后是访问根节点，最后中序遍历根节点的右子树

- 后序

  从左到右先叶子后节点的方式遍历访问左右子树，最后访问根节点

- 层序遍历:

  从根节点开始访问，从上到下逐层遍历，在同一层中，按从左到右的顺序结点逐个访问


** 基本算法

*** 排序

*冒泡排序*

1. 从第一个元素开始, 比较相邻的 =2= 个元素, 如果第一个大于第二个, 就交换位置
2. 这样一直执行到最后一个元素
3. 再从第二个元素开始, 执行上面的步骤
4. 接下来每一个元素都要重复上面的步骤, 直到排序完成


*选择排序*

1. 从 =[0, n)= 数组中找到最小或最大的元素, 将其放在起始或结束的位置(下面按最小数描述)
2. 继续从 =[1, n)= 中找最小数, 放到此次遍历的起始位置
3. 更改起始位置, 依次遍历所有元素, 直到排序完成


*插入排序*

它的工作原理是通过构建有序序列, 对于未排序数据, 在已排序序列中从后向前扫描, 找到相应位置并插入.

1. 从第一个元素开始, 该元素已排序
2. 取出下一个元素, 在已排序区从后向前扫描
3. 如果新元素小于比较的元素, 将比较的元素后移, 然后插入新元素
3. 重复上述步骤, 直到遍历结束


*归并排序*

分而治之的原理, 将数组等分, 然后分别归并排序, 最后合并

*快速排序*

快速排序使用分治法来把一个串 (list) 分为两个子串 (sub-lists), 如下:

1. 先从数列中取出一个数作为 =key= 值
2. 将比这个数小的数全部放在它的左边, 大于或等于它的数全部放在它的右边
3. 对左右两个小数列重复第二步, 直至各区间只有 =1= 个数


*** 查找

*二分查找*

元素必须是有序的, 如果是无序的则要先进行排序操作. 也称为是折半查找, 属于有序查找算法.

用给定值 =k= 先与中间结点的关键字比较, 中间结点把线形表分成两个子表, 若相等则查找成功;
若不相等, 再根据 =k= 与该中间结点关键字的比较结果确定下一步查找哪个子表,
这样递归进行, 直到查找到或查找结束发现表中没有这样的结点.

*Trie*


*** 其他

- 深拷贝与浅拷贝(python/js)
- 只遍历一次数据, 将奇偶分开, 奇数在左
- 找出数组中第二大的数, 不进行排序
- 自行实现 =strcpy=, 需要考虑那些
- 数组去重, 统计重复者的个数

#+BEGIN_SRC c
#include <stdio.h>
int
main()
{
    int list[] = {3, 6, 7, 2, 4, 9, 5, 8, 11, 13, 15};
    int i = 0;
    int count = 0;
    int length = 11;

    for (; i < length; i++) {
        if (list[i] % 2 == 0) {
            continue;
        }
        if (i == count) {
            count++;
            continue;
        }

        int tmp = list[count];
        list[count] = list[i];
        list[i] = tmp;
        count++;
    }

    for (i = 0; i < length; i++) {
        printf("%d, ", list[i]);
    }

    return 0;
}
#+END_SRC

** OS

*** 启动过程

- 参数修改
- =module= 屏蔽, 参数设定

*** 进程/线程

相关概念及区别

进程间通信

线程间通信


*** 命令行

- 使用命令替换多个文件
- 查看系统负载 =w=, =uptime= 及最后三个值的含义
- 查看系统进程 =ps aux|ps -elf=, =stat= 中 =S, s, Z= 的含义(睡眠,主进程,僵尸)
- 查看网络流量, 安装 =sysstat=, =sar= 命令
- 查看系统开启的端口 =netstat -lnp=
- 查看网络连接状态 =netstat -an=
- 如何修改 =dns=
- =iptables= IP为192.168.1.101访问本机80端口的包直接拒绝
  iptables -I INPUT -s 192.168.1.101 -p tcp --dport 80 -j REJECT
- dpkg/apt
- 环境变量
- 权限 =u+s=
- linux 启动过程
